from __future__ import annotations

import hashlib
import tempfile
import unittest
import zipfile
from pathlib import Path

from scripts.acceptance import rpgmaker_mz_prepare as prepare
from scripts.acceptance.rpgmaker_case import project_digest


class RPGMakerMZPrepareTests(unittest.TestCase):
    def test_prepare_removes_only_packaged_state_and_injects_owned_marker(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "source.zip"
            write_source(source)
            output = root / "output"
            contents = source.read_bytes()
            provenance = prepare.prepare_archive(
                source, output, hashlib.sha256(contents).hexdigest(), len(contents),
            )
            self.assertEqual("RETROM_MZ_MINIMAL_V3", provenance["transformation"]["recipe"])
            self.assertTrue(provenance["sourceVersion"].endswith("+retrom-minimal-v3"))
            self.assertEqual(2, len(provenance["transformation"]["injectedFiles"]))
            self.assertEqual(10, len(provenance["transformation"]["removedEntries"]))
            self.assertFalse((output / "save").exists())
            plugin = (output / "js/plugins/RetromMinimalAcceptance.js").read_bytes()
            self.assertIn(b"RETROM RPGMZ", plugin)
            self.assertIn(b"$gamePlayer.locate", plugin)
            self.assertIn(b"$gamePlayer.reserveTransfer(1, 19, 24, 2, 0)", plugin)
            self.assertNotIn(b"event.erase()", plugin)
            self.assertEqual(
                provenance["transformation"]["outputProjectFingerprint"], prepare.fileset_digest(output)[0],
            )
            self.assertEqual(project_digest(output), prepare.fileset_digest(output))

    def test_prepare_rejects_traversal_and_existing_output(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "unsafe.zip"
            with zipfile.ZipFile(source, "w") as archive:
                archive.writestr("nannnimo/../escape", b"bad")
            contents = source.read_bytes()
            with self.assertRaisesRegex(prepare.PrepareError, "ARCHIVE_PATH_INVALID"):
                prepare.prepare_archive(
                    source, root / "output", hashlib.sha256(contents).hexdigest(), len(contents),
                )
            existing = root / "existing"
            existing.mkdir()
            safe = root / "safe.zip"
            write_source(safe)
            safe_contents = safe.read_bytes()
            with self.assertRaisesRegex(prepare.PrepareError, "INPUT_INVALID"):
                prepare.prepare_archive(
                    safe, existing, hashlib.sha256(safe_contents).hexdigest(), len(safe_contents),
                )


def write_source(path: Path) -> None:
    entries = {
        "nannnimo/index.html": b"<html></html>",
        "nannnimo/game.rmmzproject": b"RPGMZ 1.8.1",
        "nannnimo/e\u0301.txt": b"decomposed unicode sorts after z once normalized",
        "nannnimo/z.txt": b"ascii ordering boundary",
        "nannnimo/js/plugins.js": b"// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n];\n",
        "nannnimo/js/rmmz_core.js": b'Utils.RPGMAKER_VERSION = "1.8.1";',
        "nannnimo/readme.pdf": b"documentation",
        "nannnimo/save/config.rmmzsave": b"config",
        "nannnimo/save/global.rmmzsave": b"global",
        **{f"nannnimo/save/file{index}.rmmzsave": f"save-{index}".encode() for index in range(7)},
    }
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
        for name, contents in entries.items():
            archive.writestr(name, contents)


if __name__ == "__main__":
    unittest.main()
