// Curated directory names and defaults, retained from the application catalog.
// Availability comes from the current runtime catalog, never from this list.
export const recommendedDirectoryTemplates: ReadonlyArray<readonly [platform: string, core: string, name: string, description?: string]> = [
  ["nes", "fceumm", "NES 游戏"],
  ["snes", "snes9x", "SNES 游戏"],
  ["satellaview", "snes9x", "Satellaview / BS-X 游戏"],
  ["gbc", "gambatte", "Game Boy 游戏"],
  ["sgb", "gearboy", "Super Game Boy 游戏"],
  ["gba", "mgba", "GBA 游戏"],
  ["arcade", "fbneo", "FBNeo 游戏"],
  ["arcade", "mame2003_plus", "MAME 2003 Plus 游戏"],
  ["arcade", "mame_arcade", "MAME Current 游戏", "使用 MAME Current 校验的街机 ROM，可作为旧核心的另一种运行方式。"],
  ["arcade", "fbalpha2012_cps1", "FB Alpha 2012 CPS-1 游戏"],
  ["arcade", "fbalpha2012_cps2", "FB Alpha 2012 CPS-2 游戏"],
  ["dos", "dosbox_pure", "DOS 经典游戏"],
  ["nds", "desmume2015", "Nintendo DS 游戏"],
  ["atari2600", "stella2014", "Atari 2600 游戏"],
  ["atari5200", "a5200", "Atari 5200 游戏"],
  ["atari7800", "prosystem", "Atari 7800 游戏"],
  ["lynx", "handy", "Atari Lynx 游戏"],
  ["megadrive", "genesis_plus_gx", "Mega Drive 游戏"],
  ["segacd", "genesis_plus_gx", "Sega CD / Mega-CD 游戏"],
  ["pce", "mednafen_pce", "PC Engine 游戏"],
  ["ngpc", "mednafen_ngp", "Neo Geo Pocket 游戏"],
  ["n64", "mupen64plus_next", "Nintendo 64 游戏"],
  ["psx", "pcsx_rearmed", "PlayStation 游戏"],
  ["saturn", "yabause", "Sega Saturn 游戏"],
  ["dreamcast", "flycast", "Dreamcast 游戏"],
  ["naomi", "flycast-naomi", "NAOMI 游戏"],
  ["naomi2", "flycast-naomi2", "NAOMI 2 游戏"],
  ["atomiswave", "flycast-atomiswave", "Atomiswave 游戏"],
  ["pcfx", "mednafen_pcfx", "PC-FX 游戏"],
  ["3do", "opera", "3DO 游戏"],
  ["psp", "ppsspp", "PSP 游戏"],
  ["virtualboy", "beetle_vb", "Virtual Boy 游戏"],
  ["wonderswan", "mednafen_wswan", "WonderSwan 游戏"],
  ["mastersystem", "smsplus", "Master System 游戏"],
  ["nintendo3ds", "azahar", "Nintendo 3DS 游戏"],
  ["rpgmaker", "rpgmaker", "RPG Maker 游戏"],
  ["ons", "onscripter_yuri", "ONS 游戏"],
  ["kirikiri", "kirikiri2", "KiriKiri 游戏"],
  ["butterscotch", "butterscotch", "GameMaker 游戏"],
  ["tyranoscript", "tyranoscript", "TyranoScript 游戏"],
  ["wasm4", "wasm4", "WASM-4 游戏"],
  ["j2me", "j2me", "Java ME 游戏"],
  ["tic80", "tic80", "TIC-80 游戏"],
  ["pico8", "fake08", "PICO-8 游戏"],
  ["scummvm", "scummvm", "ScummVM 游戏"],
  ["zxspectrum", "fuse", "ZX Spectrum 游戏"],
  ["c64", "vice_x64sc", "Commodore 64 游戏"],
  ["colecovision", "gearcoleco", "ColecoVision 游戏"],
  ["atarijaguar", "virtualjaguar", "Atari Jaguar 游戏"],
  ["doom", "prboom", "Doom 游戏"],
  ["c128", "vice_x128", "Commodore 128 游戏"],
  ["vic20", "vice_xvic", "Commodore VIC-20 游戏"],
  ["amiga", "puae", "Commodore Amiga 游戏"],
  ["amigacd32", "puae", "Amiga CD32 游戏"],
  ["flash", "ruffle", "Flash 游戏"],
  ["msx", "webmsx", "MSX 游戏"],
  ["x68000", "px68k", "Sharp X68000 游戏"],
  ["pc98", "np2kai", "PC-98 游戏"],
  ["openbor", "openbor", "OpenBOR 游戏"],
  ["pcecd", "mednafen_pce", "PC Engine CD 游戏"],
  ["zx81", "81", "ZX81 游戏"],
  ["amstradcpc", "cap32", "Amstrad CPC 游戏"],
  ["pet", "vice_xpet", "Commodore PET 游戏"],
  ["plus4", "vice_xplus4", "Commodore Plus/4 游戏"],
  ["cdi", "same_cdi", "Philips CD-i 游戏"],
  ["vectrex", "vecx", "Vectrex 游戏"],
  ["odyssey2", "o2em", "Odyssey² / Videopac 游戏"],
  ["intellivision", "freeintv", "Intellivision 游戏"],
  ["pc88", "quasi88", "PC-88 游戏"],
  ["neogeocd", "neocd", "Neo Geo CD 游戏"],
  ["pokemini", "gbe_plus", "Pokémon Mini 游戏"],
  ["cavestory", "nxengine", "洞窟物语"],
  ["uzebox", "uzem", "Uzebox 游戏"],
  ["bbkrpg", "gam4980", "步步高 RPG 游戏"],
  ["gamegear", "genesis_plus_gx", "Game Gear 游戏"],
  ["sg1000", "genesis_plus_gx", "SG-1000 游戏"],
  ["multivision", "genesis_plus_gx", "Multivision 游戏"],
  ["pico", "picodrive", "Sega Pico 游戏"],
  ["sega32x", "picodrive", "Sega 32X 游戏"],
  ["supergrafx", "mednafen_pce", "SuperGrafx 游戏"],
  ["gx4000", "cap32", "GX4000 游戏"],
  ["arduboy", "ardens", "Arduboy 游戏"],
  ["atari800", "atari800", "Atari 8-bit 游戏"],
  ["xegs", "atari800-xegs", "Atari XEGS 游戏"],
  ["atarist", "hatarib", "Atari ST 游戏"],
  ["bbc", "jsbeeb", "BBC Micro 游戏"],
  ["atom", "mame_atom", "Acorn Atom 游戏", "单个 .atm 快速装载文件。"],
  ["pv1000", "mame_pv1000", "PV-1000 游戏", "单张 8/16/32 KiB .bin/.rom 卡带。"],
  ["apple2", "apple2js", "Apple II 游戏"],
  ["lutro", "lutro", "Lutro 游戏"],
  ["daphne", "daphne", "Daphne 游戏"],
  ["channelf", "freechaf", "Channel F 游戏"],
  ["megaduck", "sameduck", "Mega Duck 游戏"],
  ["model3", "supermodel", "Sega Model 3 游戏"],
  ["samcoupe", "samcoupeweb", "SAM Coupé 游戏"],
  ["supervision", "potator", "Supervision 游戏"],
  ["thomson", "theodore", "Thomson 游戏"],
];
