package jobs

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
)

// CancellableJobState returns true if a job in this state can be cancelled.
func CancellableJobState(state string, retryable bool) bool {
	return state == "QUEUED" || state == "RUNNING" || state == "FAILED" && retryable
}

// RetryEligibility checks whether a job is eligible for retry.
func RetryEligibility(job Job, expectedVersion int64) error {
	if job.Version != expectedVersion || job.State != "FAILED" || !job.Retryable {
		return ErrConflict
	}
	if job.Kind == "METADATA_SCRAPE" || job.Kind == "SERVER_BIOS_IMPORT" || job.Kind == "REVIEW_BULK_APPROVE" {
		return ErrRetryViaDomain
	}
	return nil
}

// RetryInputSnapshot prepares a retry input from the previous execution.
// The executionID must be pre-generated by the caller (service layer).
func RetryInputSnapshot(previous []byte, job Job, executionID string) ([]byte, error) {
	var input retryInputEnvelope
	if json.Unmarshal(previous, &input) != nil || input.SchemaVersion != 1 ||
		input.Kind != job.Kind || input.Scope.Type != job.ScopeType || input.Scope.ID != job.ScopeID ||
		len(input.Inputs) == 0 || !json.Valid(input.Inputs) {
		return nil, ErrConflict
	}
	if input.ExecutionID == "" {
		return nil, ErrConflict
	}
	if executionID == "" {
		return nil, ErrConflict
	}
	input.ExecutionID = executionID
	encoded, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("jobs/retry input: %w", err)
	}
	return encoded, nil
}

// BuildRetryWrite constructs the full retry write payload.
// The executionID must be pre-generated by the caller (service layer).
func BuildRetryWrite(
	jobID string, expectedVersion int64, previous []byte, job Job, nowMS int64, executionID string,
) (RetryWrite, Result, error) {
	input, err := RetryInputSnapshot(previous, job, executionID)
	if err != nil {
		return RetryWrite{}, Result{}, err
	}
	digest := sha256.Sum256(input)
	executionNo := job.ExecutionNo + 1
	change := RetryWrite{
		JobID: jobID, ExpectedVersion: expectedVersion,
		ExecutionNo: executionNo, AtMS: nowMS,
		Input: input, InputDigest: hex.EncodeToString(digest[:]),
		Payload: []byte(fmt.Sprintf(
			`{"schemaVersion":1,"inputExecutionNo":%d}`, executionNo,
		)),
		Event: []byte(fmt.Sprintf(`{"executionNo":%d}`, executionNo)),
	}
	result := Result{
		Kind: job.Kind, JobID: jobID,
		State: "QUEUED", ExecutionNo: executionNo,
		Version: job.Version + 1,
	}
	return change, result, nil
}

// NeedsDomainCancel reports whether this job kind's cancellation
// should be handled by a domain-specific handler rather than
// the generic cancel path.
func NeedsDomainCancel(_ string, hasDomainHandler bool) bool {
	return hasDomainHandler
}

type retryInputEnvelope struct {
	SchemaVersion int             `json:"schemaVersion"`
	Kind          string          `json:"kind"`
	Scope         retryInputScope `json:"scope"`
	ExecutionID   string          `json:"executionId"`
	Inputs        json.RawMessage `json:"inputs"`
}

type retryInputScope struct {
	Type string `json:"type"`
	ID   string `json:"id"`
}
