package runtimeprovider

import "context"

// ReconcileCommand captures the projection candidate and current timestamp.
// AuditID must be pre-generated by the service layer.
type ReconcileCommand struct {
	Candidate Projection
	AuditID   string
	NowMS     int64
}

type Repository interface {
	CommitReconcile(context.Context, ReconcileCommand) error
}
type (
	TargetIdentity struct{ ProviderID, TargetID string }
	CurrentState   struct {
		Providers     map[string]CurrentProvider
		Targets       []TargetIdentity
		CatalogSHA256 string
	}
)

type Publication struct {
	Candidate        Projection
	RemovedTargets   []TargetIdentity
	RemovedProviders []string
	AtMS             int64
}
type Audit struct {
	ID       string
	DiffJSON []byte
	AtMS     int64
}
