"""Digest explicit paired source, self-contained host tool and verified Provider inputs."""
import argparse
import hashlib
import json
import os
from pathlib import Path
from runtime_input_manifest import load_manifest, manifest_bytes
from runtime_inputs import prepare, verify_prepared
from runtime_provider_cache import default_cache_root

ROOT = Path(__file__).resolve().parents[1]
GENERATED_GO_PATHS = {
    "internal/httpapi/generated/models.gen.go",
    "internal/httpapi/generated/server.gen.go",
    "internal/httpapi/generated/spec.gen.go",
}
GENERATED_GO_MARKER = b"// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT."


def tree_digest(directory: Path, selected: list[str] | None = None, *, generated_go: bool = False) -> str:
    if not directory.is_dir():
        raise ValueError("IMAGE_INPUT_DIRECTORY_REQUIRED")
    digest = hashlib.sha256()
    roots = [directory / name for name in selected] if selected else [directory]
    for root in roots:
        if not root.exists():
            raise ValueError("IMAGE_INPUT_FILE_REQUIRED")
        files = [root] if root.is_file() else sorted(root.rglob("*"))
        for file in files:
            if file.is_symlink():
                raise ValueError("IMAGE_INPUT_SYMLINK_FORBIDDEN")
            if not file.is_file():
                continue
            if generated_go and file.relative_to(directory).as_posix() in GENERATED_GO_PATHS:
                with file.open("rb") as stream:
                    if GENERATED_GO_MARKER not in stream.read(512).splitlines():
                        raise ValueError("IMAGE_GENERATED_SOURCE_MARKER_INVALID")
                continue
            digest.update(file.relative_to(directory).as_posix().encode())
            with file.open("rb") as stream:
                for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                    digest.update(chunk)
    return digest.hexdigest()


def inputs() -> tuple[Path, Path, Path]:
    manifest_path = ROOT / "data/runtime-inputs.json"
    manifest = load_manifest(manifest_path)
    tool_value, providers_value = (os.environ.get(key, "") for key in ("RETROM_RUNTIME_TOOL_INPUT", "RETROM_PROVIDER_INPUT"))
    if bool(tool_value) != bool(providers_value):
        raise ValueError("IMAGE_INPUT_PAIRED_DIRECTORIES_REQUIRED")
    if tool_value:
        tool, providers = Path(tool_value).resolve(), Path(providers_value).resolve()
        if tool.name != "tool" or providers.name != "providers" or tool.parent != providers.parent:
            raise ValueError("IMAGE_INPUT_PREPARED_SET_REQUIRED")
        verify_prepared(tool.parent, manifest)
    else:
        archive_root = os.environ.get("RETROM_RUNTIME_INPUT_ARCHIVE_ROOT")
        prepared = prepare(manifest_path, ROOT / ".cache/runtime-inputs", default_cache_root(ROOT),
                           archive_root=Path(archive_root) if archive_root else None,
                           base_url=os.environ.get("RETROM_RUNTIME_INPUT_BASE_URL", ""))
        tool, providers = prepared / "tool", prepared / "providers"
    return tool, providers, Path(os.environ.get("RETROM_DEPENDENCY_ROOT", ROOT / "data")).resolve()


def value() -> dict[str, object]:
    tool, providers, dependencies = inputs()
    package = json.loads((tool / "package.json").read_text())
    if not (tool / "scripts/runtime-cli.mjs").is_file() or not (tool / "dist/runtime/index.js").is_file():
        raise ValueError("IMAGE_RUNTIME_TOOL_INCOMPLETE")
    if not package.get("dependencies") or not (tool / "node_modules").is_dir():
        raise ValueError("IMAGE_RUNTIME_DEPENDENCIES_INCOMPLETE")
    source_roots = ["Dockerfile", ".dockerignore", "go.mod", "go.sum", "api", "cmd", "internal", "migrations",
                    "scripts/openapi-bundle", "scripts/build-image.sh", "scripts/image_input_digest.py",
                    "scripts/prepare_image_inputs.py", "scripts/runtime_inputs.py", "scripts/runtime_input_manifest.py",
                    "scripts/runtime_input_transport.py", "scripts/runtime_input_archive.py",
                    "scripts/runtime_provider_bundle.py", "scripts/runtime_provider_contract.py", "scripts/runtime_provider_io.py",
                    "web/Dockerfile", "web/.dockerignore", "web/package.json",
                    "web/package-lock.json", "web/next.config.ts", "web/next-env.d.ts", "web/tsconfig.json",
                    "web/postcss.config.mjs", "web/proxy.ts", "web/app", "web/features", "web/components",
                    "web/lib", "web/styles", "web/public", "web/e2e", "web/scripts", "web/eslint.config.mjs",
                    "web/next.config.test.ts", "web/playwright.config.ts", "web/vitest.config.ts", "web/vitest.setup.ts"]
    return {"schemaVersion": 1, "sourceSha256": tree_digest(ROOT, source_roots, generated_go=True),
            "webBackendOrigin": os.environ.get("NEXT_BACKEND_ORIGIN", "http://retrom:8080"),
            "runtimeInputsSha256": hashlib.sha256(manifest_bytes(load_manifest(ROOT / "data/runtime-inputs.json"))).hexdigest(),
            "runtimeToolSha256": tree_digest(tool),
            "providerSha256": tree_digest(providers, ["active.json", "installed"]),
            "dependencySha256": tree_digest(dependencies, ["auth/password-blocklists"])}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = value()
    if args.check:
        tool, _, _ = inputs()
        verify_prepared(tool.parent, load_manifest(ROOT / "data/runtime-inputs.json"),
                        node=os.environ.get("RETROM_NODE", "node"))
    encoded = json.dumps(result, sort_keys=True, separators=(",", ":")).encode()
    print(hashlib.sha256(encoded).hexdigest())


if __name__ == "__main__":
    main()
