"""Image contexts cannot bypass the repository's complete paired input pin."""
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from runtime_inputs import prepare
from test_runtime_inputs import paired_fixture

import image_input_digest


class ImagePinTests(unittest.TestCase):
    def test_generated_go_is_not_a_docker_source_input(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "api").mkdir()
            (root / "internal").mkdir()
            authority = root / "api/openapi.yaml"
            authority.write_text("authoritative input")
            before = image_input_digest.tree_digest(root, ["api", "internal"], generated_go=True)
            generated = root / "internal/httpapi/generated"
            generated.mkdir(parents=True)
            for name in ["models.gen.go", "server.gen.go", "spec.gen.go"]:
                (generated / name).write_text("// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.\npackage generated\n")
            self.assertEqual(before, image_input_digest.tree_digest(root, ["api", "internal"], generated_go=True))
            authority.write_text("changed authoritative input")
            self.assertNotEqual(before, image_input_digest.tree_digest(root, ["api", "internal"], generated_go=True))
            (generated / "models.gen.go").write_text("package manuallyWritten\n")
            with self.assertRaisesRegex(ValueError, "GENERATED_SOURCE_MARKER_INVALID"):
                image_input_digest.tree_digest(root, ["api", "internal"], generated_go=True)

    def test_explicit_contexts_match_repository_pin_and_authentic_archives(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            pin, archives, manifest, _ = paired_fixture(root, formal=False)
            prepared = prepare(pin, root / "output", root / "cache", archive_root=archives)
            (root / "data").mkdir()
            (root / "data/runtime-inputs.json").write_bytes(pin.read_bytes())
            environment = {"RETROM_RUNTIME_TOOL_INPUT": str(prepared / "tool"), "RETROM_PROVIDER_INPUT": str(prepared / "providers")}
            with patch.object(image_input_digest, "ROOT", root), patch.dict(os.environ, environment):
                self.assertEqual(image_input_digest.inputs()[:2], (prepared / "tool", prepared / "providers"))
                (prepared / "tool/dist/runtime/index.js").write_text("export const version = 'another valid tool';")
                with self.assertRaisesRegex(ValueError, "TOOL_ARCHIVE_MISMATCH"):
                    image_input_digest.inputs()

    def test_mutable_manifest_environment_cannot_replace_checked_in_pin(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            pin, archives, manifest, _ = paired_fixture(root, formal=False)
            prepared = prepare(pin, root / "output", root / "cache", archive_root=archives)
            manifest["sourceTreeSha256"] = "d" * 64
            (root / "data").mkdir()
            (root / "data/runtime-inputs.json").write_text(json.dumps(manifest))
            with patch.object(image_input_digest, "ROOT", root), patch.dict(os.environ, {
                    "RETROM_RUNTIME_TOOL_INPUT": str(prepared / "tool"), "RETROM_PROVIDER_INPUT": str(prepared / "providers"),
                    "RETROM_RUNTIME_INPUT_MANIFEST": str(pin)}):
                with self.assertRaisesRegex(ValueError, "PREPARED_PIN_MISMATCH"):
                    image_input_digest.inputs()


if __name__ == "__main__":
    unittest.main()
