"""Required managed Target coverage; logical input references carry no operator data."""
COMMON_SCENARIOS = {"preview-publish", "cold", "warm-new-launch", "save-restore-input", "exit", "performance-five-cold-warm"}
RANGE_SCENARIOS = {"concurrent-read", "metadata-no-body", "trace-10000", "read-exit", "fault-range-200", "fault-identity-412",
                   "fault-short-body", "worker-termination", "cache-corruption", "cache-denied"}
# Generated by retrom-runtime/scripts/content-io/target-catalog.mjs. No second hand-maintained Target list.
import json
from pathlib import Path

DECLARATIONS = Path(__file__).resolve().parents[2] / "tests/fixtures/content-io/target-declarations.json"
MANAGED_DECLARATIONS = [row for row in json.loads(DECLARATIONS.read_text())["targets"] if row["mode"] in {"RANGE", "EAGER", "ON_OPEN"}]
TARGET_DECLARATIONS = {row["targetId"]: row for row in MANAGED_DECLARATIONS}
if len(TARGET_DECLARATIONS) != len(MANAGED_DECLARATIONS):
    raise ValueError("CONTENT_IO_CATALOG_AMBIGUOUS_TARGET")
TARGET_MODES = {target: ("WORKSPACE" if row["delivery"] == "WORKSPACE_FILE" else
                         "PROJECT" if row["mode"] == "EAGER" and row["gameKind"] == "FILE_TREE" else row["mode"])
                for target, row in TARGET_DECLARATIONS.items()}
EXTRA_SCENARIOS = {
    "scummvm": {"multiple-files", "zero-file", "same-size-path-isolation"},
    "ppsspp": {"iso-and-cso", "strict-etag-and-length"},
    "play-ps2": {"device-done-error"},
    "kirikiri2-kag": {"xp3-and-zip", "main-jspi-and-pthread", "overlay-isolation"},
    "onscripter-yuri": {"unopened-file-no-body", "runtime-open-no-loading-overlay"},
    "butterscotch-gamemaker": {"workspace-denied", "workspace-corruption", "workspace-atomic-commit", "save-root-isolation"},
    "nxengine": {"required-file-set", "unrelated-file-no-body"},
}


def required_scenarios(target: str) -> set[str]:
    mode = TARGET_MODES[target]
    scenarios = COMMON_SCENARIOS | (RANGE_SCENARIOS if mode == "RANGE" else {"cache-denied", "size-boundaries"})
    if mode in {"EAGER", "WORKSPACE", "PROJECT"}:
        scenarios |= {"eager-progress"}
    if target in {"rpgmaker-xp", "rpgmaker-vx", "rpgmaker-vx-ace"}:
        scenarios |= {"retired-rtp-boundary", "native-thread-start-stop"}
    if TARGET_DECLARATIONS[target]["checkpointSemantics"] == "NO_SAVE":
        scenarios = (scenarios - {"save-restore-input"}) | {"input-no-save"}
    return scenarios | EXTRA_SCENARIOS.get(target, set())
