import assert from "node:assert/strict";
import {mkdir, writeFile} from "node:fs/promises";
import {join, resolve} from "node:path";
import {chromium, expect} from "../../web/node_modules/@playwright/test/index.mjs";
import sharp from "../../web/node_modules/sharp/dist/index.cjs";
import {fantasyClient, approveCart} from "./fantasy_product_client.mjs";
import {importComputer} from "./computer_product_client.mjs";

const base = process.env.RETROM_ACCEPTANCE_BASE_URL;
const directory = resolve(process.env.RETROM_ACCEPTANCE_CASE_DIR ?? ".artifacts/dos-launch-options-ui");
const screenshots = join(directory, "screenshots");
await mkdir(screenshots, {recursive: true});
const report = {schemaVersion: 1, caseId: "ACC-UI-003", status: "FAIL"};
const browser = await chromium.launch({executablePath: process.env.RETROM_CHROME_EXECUTABLE, headless: true});
const context = await browser.newContext({viewport: {width: 2560, height: 1440}, deviceScaleFactor: 1.5});
try {
  assert.ok(base, "DOS_UI_BASE_URL_REQUIRED");
  const client = await fantasyClient(context, base);
  const review = await importComputer(client, "dos", "dosbox_pure", resolve("testdata/public-roms/dos-cache/dos-cache.zip"));
  const game = await approveCart(client, review.itemId);
  report.gameId = game.gameId;
  const page = await context.newPage();
  await page.goto(`${base}/games/${game.gameId}`);
  const options = page.locator(".launch-options");
  const loading = page.getByRole("combobox", {name: "内容加载", exact: true});
  const program = page.getByRole("combobox", {name: "启动程序", exact: true});
  await expect(loading).toBeEnabled();
  await expect(page.locator(".game-detail-meta:empty")).toHaveCount(0);
  report.heroHeight = (await page.locator(".game-detail-hero").boundingBox()).height;
  assert.ok(report.heroHeight <= 480, "SHORT_TITLE_DOS_HERO_MUST_REMAIN_COMPACT");
  const loadingTab = page.getByRole("tab", {name: "内容加载", exact: true});
  const programTab = page.getByRole("tab", {name: "启动程序", exact: true});
  await expect(page.getByRole("tablist")).toHaveText(/内容加载\s*\/\s*启动程序/);
  await expect(page.getByRole("combobox")).toHaveCount(1);
  await expect(program).toHaveCount(0);
  // Tabs remain explicit choices at every desktop container width.
  const middleWidth = width => page.locator(".game-detail-main").evaluate((element, value) => {element.style.maxWidth = `${value}px`;}, width);
  await middleWidth(700);
  await expect(options).toHaveClass(/is-tabbed/);
  const boxes = await Promise.all([loading.boundingBox(), page.locator(".launch-actions button").last().boundingBox()]);
  assert.ok(Math.abs(boxes[0].x + boxes[0].width - boxes[1].x - boxes[1].width) < 1, "DOS_LOADING_BUTTON_RIGHT_ALIGNMENT");
  await page.screenshot({path: join(screenshots, "dos-options-wide-4k.png")});
  await programTab.click();
  await expect(program).toHaveValue("CACHE.COM");
  await expect(page.getByRole("combobox")).toHaveCount(1);
  await expect(loading).toHaveCount(0);
  await middleWidth(400);
  await expect(options).toHaveClass(/is-tabbed/);
  await expect(programTab).toHaveAttribute("aria-selected", "true");
  await loadingTab.click();
  await expect(loadingTab).toHaveAttribute("aria-selected", "true");
  await loading.selectOption("PRELOAD");
  await expect(loading).toHaveValue("PRELOAD");
  const before = await options.boundingBox();
  await programTab.click();
  await expect(loading).toHaveCount(0);
  await expect(page.locator(".launch-option-panel.is-inactive")).toHaveAttribute("inert", "");
  await program.selectOption("");
  await expect(program).toHaveValue("");
  const after = await options.boundingBox();
  assert.equal(before.height, after.height, "DOS_TAB_SWITCH_MUST_PRESERVE_HEIGHT");
  await programTab.focus(); await page.keyboard.press("ArrowLeft");
  await expect(loadingTab).toBeFocused();
  await expect(loading).toHaveValue("PRELOAD");
  await page.keyboard.press("End"); await expect(programTab).toBeFocused();
  await page.keyboard.press("Home"); await expect(loadingTab).toBeFocused();
  await page.keyboard.press("ArrowRight"); await expect(programTab).toBeFocused();
  await page.keyboard.press("Tab"); await expect(program).toBeFocused();
  await page.screenshot({path: join(screenshots, "dos-options-tabs-4k.png")});
  await middleWidth(700);
  await expect(page.getByRole("tablist")).toHaveCount(1);
  await expect(program).toHaveValue(""); await expect(loading).toHaveCount(0);
  await middleWidth(400);
  await loadingTab.click(); await expect(loading).toHaveValue("PRELOAD");
  await page.reload();
  await programTab.click();
  await expect(program).toHaveValue("CACHE.COM"); // Changing a field does not persist a DOS launch choice.
  await loadingTab.click();
  await expect(loading).toHaveValue("PRELOAD");
  await page.setViewportSize({width: 390, height: 844});
  await page.getByRole("button", {name: "启动选项", exact: true}).click();
  await expect(page.getByRole("tablist")).toHaveCount(0);
  await expect(loading).toHaveValue("PRELOAD"); await expect(program).toHaveValue("CACHE.COM");
  await page.screenshot({path: join(screenshots, "dos-options-mobile.png")});
  const metadata = await sharp(join(screenshots, "dos-options-tabs-4k.png")).metadata();
  assert.equal(metadata.width, 3840); assert.equal(metadata.height, 2160);
  report.dimensions = {width: metadata.width, height: metadata.height, dpr: 1.5};
  report.wide = boxes; report.compact = {before, after};
  report.status = "PASS";
} catch (error) {report.error = error.message; throw error;}
finally {
  await writeFile(join(directory, "dos-launch-options-ui.json"), JSON.stringify(report, null, 2) + "\n");
  await context.close(); await browser.close();
}
