#!/usr/bin/env python3
"""Prepare the licensed MZ acceptance project from the pinned official ZIP."""

from __future__ import annotations

import argparse
import hashlib
import json
import stat
import unicodedata
import zipfile
from pathlib import Path, PurePosixPath


SOURCE_SIZE_BYTES = 98_413_632
SOURCE_SHA256 = "48c5ec13b6a136e7ce1b6f0f9d19d493ed28599b9fea899fa0a78ab356cbf49b"
SOURCE_VERSION = "nannnimo.zip@S3-pdevmVYtsEjgmApT19h4U2RsKDZtjXwl+retrom-minimal-v4"
SOURCE_URL = "https://cdn.tkool.jp/updata/nannnimo.zip"
LICENSE_URL = "https://rpgmakerofficial.com/product/mz/download/dlc/dl_04.html"
WRAPPER = "nannnimo"
ORIGINAL_PLUGINS_SHA256 = "2116dfda46bec80e7fab4b7e97b94931c47c9fb3642e6fa4c1625d0016b448a0"
SAVE_FILES = {
    "save/config.rmmzsave", "save/global.rmmzsave",
    *(f"save/file{index}.rmmzsave" for index in range(7)),
}
PLUGINS_JS = b'''// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
    {
        "name": "RetromMinimalAcceptance",
        "status": true,
        "description": "Deterministic marker and fixture variable for Retrom's licensed MZ acceptance copy.",
        "parameters": {}
    }
];
'''
PLUGIN_JS = b'''/*:
 * @target MZ
 * @plugindesc Deterministic marker and fixture variable for Retrom's licensed MZ acceptance copy.
 * @author Retrom
 */

(() => {
    "use strict";

    const marker = "RETROM RPGMZ";
    const markerColor = "#40d0ff";

    Scene_Boot.prototype.startNormalGame = function() {
        this.checkPlayerLocation();
        DataManager.setupNewGame();
        $gamePlayer.reserveTransfer(1, 19, 24, 2, 0);
        Window_TitleCommand.initCommandPosition();
        SceneManager.goto(Scene_Map);
    };

    const createDisplayObjects = Scene_Map.prototype.createDisplayObjects;
    Scene_Map.prototype.createDisplayObjects = function() {
        createDisplayObjects.call(this);
        const bitmap = new Bitmap(360, 72);
        bitmap.fillRect(0, 0, 360, 72, "#101827");
        bitmap.fillRect(0, 0, 360, 8, markerColor);
        bitmap.fontSize = 32;
        bitmap.textColor = "#ffffff";
        bitmap.drawText(marker, 20, 16, 320, 44, "left");
        const sprite = new Sprite(bitmap);
        sprite.x = 24;
        sprite.y = 24;
        this.addChild(sprite);
        this._retromAcceptanceMarker = sprite;
    };

    const update = Scene_Map.prototype.update;
    Scene_Map.prototype.update = function() {
        update.call(this);
        if (Input.isTriggered("ok")) {
            const current = Number($gameVariables.value(1)) || 0;
            const width = $gameMap.width();
            const nextX = width > 1 ? ($gamePlayer.x + 1) % width : $gamePlayer.x;
            $gamePlayer.locate(nextX, $gamePlayer.y);
            $gameVariables.setValue(1, current === 0 ? 1 : current === 1 ? 2 : 1);
            SoundManager.playOk();
        }
    };
})();
'''


class PrepareError(RuntimeError):
    pass


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def safe_relative_name(info: zipfile.ZipInfo) -> str:
    name = unicodedata.normalize("NFC", info.filename)
    if "\\" in name or "\0" in name or name.startswith("/"):
        raise PrepareError("RPG_MZ_PREPARE_ARCHIVE_PATH_INVALID")
    path = PurePosixPath(name)
    if not path.parts or any(part in {"", ".", ".."} for part in path.parts):
        raise PrepareError("RPG_MZ_PREPARE_ARCHIVE_PATH_INVALID")
    mode = info.external_attr >> 16
    if mode and stat.S_ISLNK(mode):
        raise PrepareError("RPG_MZ_PREPARE_ARCHIVE_SYMLINK_FORBIDDEN")
    if path.parts[0] != WRAPPER:
        raise PrepareError("RPG_MZ_PREPARE_WRAPPER_INVALID")
    return PurePosixPath(*path.parts[1:]).as_posix()


def fileset_digest(root: Path) -> tuple[str, int, int]:
    entries = list(root.rglob("*"))
    if any(path.is_symlink() for path in entries):
        raise PrepareError("RPG_MZ_PREPARE_OUTPUT_SYMLINK_FORBIDDEN")
    files = sorted(
        (unicodedata.normalize("NFC", path.relative_to(root).as_posix()), path)
        for path in entries if path.is_file()
    )
    digest = hashlib.sha256(b"RETROM_FILESET_V1\0")
    total = 0
    logical_names: set[str] = set()
    for logical_name, path in files:
        if logical_name in logical_names:
            raise PrepareError("RPG_MZ_PREPARE_OUTPUT_PATH_COLLISION")
        logical_names.add(logical_name)
        contents = path.read_bytes()
        for value in (b"PROJECT_FILE", logical_name.encode()):
            digest.update(len(value).to_bytes(4, "big"))
            digest.update(value)
        digest.update(hashlib.sha256(contents).digest())
        digest.update(len(contents).to_bytes(8, "big"))
        digest.update(b"\0")
        total += len(contents)
    return digest.hexdigest(), len(files), total


def removed_entry(logical_name: str, contents: bytes, reason: str) -> dict[str, object]:
    return {
        "logicalName": logical_name, "reason": reason,
        "sizeBytes": len(contents), "sha256": sha256_bytes(contents),
    }


def prepare_archive(
    source_zip: Path,
    output_root: Path,
    expected_sha256: str = SOURCE_SHA256,
    expected_size_bytes: int = SOURCE_SIZE_BYTES,
) -> dict[str, object]:
    if not source_zip.is_file() or source_zip.is_symlink() or output_root.exists():
        raise PrepareError("RPG_MZ_PREPARE_INPUT_INVALID")
    source = source_zip.read_bytes()
    if len(source) != expected_size_bytes or sha256_bytes(source) != expected_sha256:
        raise PrepareError("RPG_MZ_PREPARE_SOURCE_IDENTITY_MISMATCH")
    output_root.mkdir(parents=True)
    removed: list[dict[str, object]] = []
    seen: set[str] = set()
    root_pdf_count = 0
    with zipfile.ZipFile(source_zip) as archive:
        for info in archive.infolist():
            logical_name = safe_relative_name(info)
            if not logical_name or info.is_dir():
                continue
            key = unicodedata.normalize("NFKC", logical_name).casefold()
            if key in seen:
                raise PrepareError("RPG_MZ_PREPARE_ARCHIVE_PATH_COLLISION")
            seen.add(key)
            contents = archive.read(info)
            reason = None
            if logical_name in SAVE_FILES:
                reason = "PACKAGED_SAVE_EXCLUDED"
            elif "/" not in logical_name and logical_name.lower().endswith(".pdf"):
                reason = "ROOT_DOCUMENTATION_EXCLUDED"
                root_pdf_count += 1
            if reason:
                removed.append(removed_entry(logical_name, contents, reason))
                continue
            destination = output_root / logical_name
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(contents)
    if root_pdf_count != 1 or {str(item["logicalName"]) for item in removed if item["reason"] == "PACKAGED_SAVE_EXCLUDED"} != SAVE_FILES:
        raise PrepareError("RPG_MZ_PREPARE_EXCLUSION_SET_INVALID")
    plugins_path = output_root / "js/plugins.js"
    injected_path = output_root / "js/plugins/RetromMinimalAcceptance.js"
    if not plugins_path.is_file() or sha256_bytes(plugins_path.read_bytes()) != ORIGINAL_PLUGINS_SHA256 or \
            injected_path.exists():
        raise PrepareError("RPG_MZ_PREPARE_PLUGIN_BASE_INVALID")
    plugins_path.write_bytes(PLUGINS_JS)
    injected_path.parent.mkdir(parents=True, exist_ok=True)
    injected_path.write_bytes(PLUGIN_JS)
    fingerprint, file_count, total_bytes = fileset_digest(output_root)
    injected = [
        {"logicalName": "js/plugins.js", "sizeBytes": len(PLUGINS_JS), "sha256": sha256_bytes(PLUGINS_JS)},
        {"logicalName": "js/plugins/RetromMinimalAcceptance.js", "sizeBytes": len(PLUGIN_JS),
         "sha256": sha256_bytes(PLUGIN_JS)},
    ]
    return {
        "schemaVersion": 1,
        "kind": "LICENSED_EXTERNAL_WEB_DEPLOYMENT",
        "marker": "RETROM RPGMZ", "markerRgb": [64, 208, 255],
        "licenseBasis": "RPG_MAKER_MZ_OFFICIAL_SAMPLE_MODIFICATION_TERMS",
        "licenseUrl": LICENSE_URL, "sourceUrl": SOURCE_URL,
        "sourceVersion": SOURCE_VERSION, "sourceSha256": expected_sha256,
        "transformation": {
            "schemaVersion": 1, "recipe": "RETROM_MZ_MINIMAL_V4",
            "tool": "scripts/acceptance/rpgmaker_mz_prepare.py",
            "sourceSizeBytes": expected_size_bytes,
            "removedEntries": sorted(removed, key=lambda item: str(item["logicalName"])),
            "injectedFiles": injected,
            "outputProjectFingerprint": fingerprint,
            "outputFileCount": file_count, "outputTotalBytes": total_bytes,
        },
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-zip", required=True, type=Path)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--provenance-output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.provenance_output.exists() or not args.provenance_output.parent.is_dir():
        raise PrepareError("RPG_MZ_PREPARE_PROVENANCE_OUTPUT_INVALID")
    provenance = prepare_archive(args.source_zip, args.output_root)
    args.provenance_output.write_text(
        json.dumps(provenance, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8",
    )
    print(json.dumps({
        "status": "PASS", "projectFingerprint": provenance["transformation"]["outputProjectFingerprint"],
        "fileCount": provenance["transformation"]["outputFileCount"],
        "totalBytes": provenance["transformation"]["outputTotalBytes"],
    }, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
